name: thecourierapp
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dotted_decoration: ^2.0.0
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  flutter:
    sdk: flutter
  flutter_google_places_sdk: ^0.3.2+8
  flutter_launcher_icons: ^0.13.0
  flutter_local_notifications: ^13.0.0
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.4
  flutter_swipe_button: ^2.1.1+1
  flutter_vector_icons: ^2.0.0
  fluttertoast: ^8.2.1
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  google_maps_flutter: ^2.2.5
  http: ^0.13.5
  image_picker: ^0.8.7+1
  image_picker_ios: ^0.8.7+2
  images_picker: ^1.2.11
  intl: ^0.18.0
  local_auth: ^2.1.6
  package_info_plus: ^3.0.3
  pinput: ^2.2.31
  places_service: ^0.1.3
  provider: ^6.0.5
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.1.10
  url_launcher_ios: ^6.1.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/newlogo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: TTNorms
      fonts:
        - asset: assets/fonts/TTNorms-Regular.otf
        - asset: assets/fonts/TTNorms-Bold.otf
          weight: 700
