// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdwF9cF9d7B6MIov5rw4JVUfXEST2TS9w',
    appId: '1:425291919517:web:c681be83aed7ddd55d6474',
    messagingSenderId: '425291919517',
    projectId: 'thecarcourier-1',
    authDomain: 'thecarcourier-1.firebaseapp.com',
    storageBucket: 'thecarcourier-1.appspot.com',
    measurementId: 'G-WFFPBYLF9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZNppUJ5EwGWSjepA6kBWbmQBQL2wUHLg',
    appId: '1:425291919517:android:268d7633796fcaab5d6474',
    messagingSenderId: '425291919517',
    projectId: 'thecarcourier-1',
    storageBucket: 'thecarcourier-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdOFwxCv9unC7HVDU7B0yIFWZzkNW-oBo',
    appId: '1:425291919517:ios:49868a16bd9599735d6474',
    messagingSenderId: '425291919517',
    projectId: 'thecarcourier-1',
    storageBucket: 'thecarcourier-1.appspot.com',
    androidClientId: '425291919517-m8ltgasneeuen406q59tv3tick7rch25.apps.googleusercontent.com',
    iosClientId: '425291919517-46rev0j0jskhsihg65fo8nnpd7a2gh1a.apps.googleusercontent.com',
    iosBundleId: 'com.ibyte.thecourierapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdOFwxCv9unC7HVDU7B0yIFWZzkNW-oBo',
    appId: '1:425291919517:ios:49868a16bd9599735d6474',
    messagingSenderId: '425291919517',
    projectId: 'thecarcourier-1',
    storageBucket: 'thecarcourier-1.appspot.com',
    androidClientId: '425291919517-m8ltgasneeuen406q59tv3tick7rch25.apps.googleusercontent.com',
    iosClientId: '425291919517-46rev0j0jskhsihg65fo8nnpd7a2gh1a.apps.googleusercontent.com',
    iosBundleId: 'com.ibyte.thecourierapp',
  );
}
